# Generated by Django 5.1.1 on 2024-10-07 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0004_remove_otp_is_verified_otp_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 7, 10, 36, 4, 476361, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
