# Generated by Django 5.1.1 on 2024-10-08 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0005_alter_otp_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 8, 10, 30, 46, 129034, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
