# Generated by Django 5.1.1 on 2024-10-07 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("User", "0004_remove_otp_is_verified_otp_expires_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("house", "House"),
                            ("apartment", "Apartment"),
                            ("commercial", "Commercial"),
                            ("land", "Land"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=10)),
                ("country", models.CharField(default="India", max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("area_in_sqft", models.DecimalField(decimal_places=2, max_digits=7)),
                ("bedrooms", models.IntegerField(blank=True, null=True)),
                ("bathrooms", models.IntegerField(blank=True, null=True)),
                ("parking_spaces", models.IntegerField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.user"
                    ),
                ),
            ],
        ),
    ]
